### ISSUE TITLE
Settings.apk decompile error 

### ISSUE THREAD

**Issue by igobig** [BurgerZ/jBART#137] opened 2016-01-07 13:01 UTC
Process log:
[07.01.2016 19:50:39] I: 
[07.01.2016 19:50:39] I: 
[07.01.2016 19:50:39] I: THURSDAY 07.01.2016 19:50:39
[07.01.2016 19:50:39] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[07.01.2016 19:50:39] I: www: http://burgerz.pro
[07.01.2016 19:50:39] I: Email: az.burgerz@gmail.com
[07.01.2016 19:50:39] I: All Rights Reserved
[07.01.2016 19:50:39] I: **************************************************
i have decomplie settings.apk on rom http://bigota.d.miui.com/5.12.31/miui_HMNote3_5.12.31_834c1b25fc_5.0.zip

this show error in below

[07.01.2016 19:50:39] I: Welcome to jBART v3h build 20151230.03
[07.01.2016 19:50:39] I: **************************************************
[07.01.2016 19:50:39] I: Java version: 1.8.0_45-internal
[07.01.2016 19:50:39] I: OS name: Linux
[07.01.2016 19:50:39] I: OS version: 3.13.0-66-generic
[07.01.2016 19:50:39] I: OS arch: 64 bit
[07.01.2016 19:50:39] I: Home directory: /home/igobig/Desktop/jBART-master-3H/
[07.01.2016 19:50:39] I: 
[07.01.2016 19:50:42] W: Empty config: repo.miui.v7.extra.conf
[07.01.2016 19:50:42] W: Empty config: repo.miui.v7.patch.conf
[07.01.2016 19:50:42] W: Empty config: repo.miui.v7.extra.conf
[07.01.2016 19:50:42] W: Empty config: repo.miui.v7.patch.conf
[07.01.2016 19:50:59] I: String index out of range: -9
[07.01.2016 19:51:50] I: Loaded NXT patcher config: /home/igobig/Desktop/jBART-master-3H/data/patches/nxt/ContactsProvider/T9.ptch
[07.01.2016 19:51:50] I: 
[07.01.2016 19:51:50] I: 
[07.01.2016 19:51:50] I: THURSDAY 07.01.2016 19:51:50
[07.01.2016 19:51:50] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[07.01.2016 19:51:50] I: www: http://burgerz.pro
[07.01.2016 19:51:50] I: Email: az.burgerz@gmail.com
[07.01.2016 19:51:50] I: All Rights Reserved
[07.01.2016 19:51:50] I: **************************************************
[07.01.2016 19:51:50] I: Welcome to jBART v3h build 20151230.03
[07.01.2016 19:51:50] I: **************************************************
[07.01.2016 19:51:50] I: Java version: 1.8.0_45-internal
[07.01.2016 19:51:50] I: OS name: Linux
[07.01.2016 19:51:50] I: OS version: 3.13.0-66-generic
[07.01.2016 19:51:50] I: OS arch: 64 bit
[07.01.2016 19:51:50] I: Home directory: /home/igobig/Desktop/jBART-master-3H/
[07.01.2016 19:51:50] I: 
[07.01.2016 19:51:50] I: 
[07.01.2016 19:51:50] I: ******** Installing frameworks ********
[07.01.2016 19:51:50] I: **** Decompiling Settings.apk ****
[07.01.2016 19:51:50] I: File apktool.jar not found. Using apktool-3.0.9-bz-small.jar
[07.01.2016 19:51:50] I: I: Loading resource table...
[07.01.2016 19:51:51] I: I: Decoding Shared Library (com.mediatek), pkgId: 8
[07.01.2016 19:51:51] I: I: Decoding Shared Library (miui), pkgId: 16
[07.01.2016 19:51:51] I: I: Decoding Shared Library (android.miui), pkgId: 17
[07.01.2016 19:51:51] I: I: Decoding Shared Library (miui.system), pkgId: 18
[07.01.2016 19:51:51] I: I: Decoding AndroidManifest.xml with resources...
[07.01.2016 19:51:51] I: I: Loading resource table from file: /home/igobig/Desktop/jBART-master-3H/data/frameworks/1.apk
[07.01.2016 19:51:51] I: I: Loading resource table from file: /home/igobig/Desktop/jBART-master-3H/data/frameworks/16.apk
[07.01.2016 19:51:51] I: I: Decoding Shared Library (androidhwext), pkgId: 15
[07.01.2016 19:51:51] I: I: Package: com.android.settings (com.android.settings)
[07.01.2016 19:51:51] I: I: Regular manifest package...
[07.01.2016 19:51:52] I: I: Decoding file-resources...
[07.01.2016 19:51:52] I: I: Loading resource table from file: /home/igobig/Desktop/jBART-master-3H/data/frameworks/17.apk
[07.01.2016 19:51:52] I: I: Decoding Shared Library (miui), pkgId: 16
[07.01.2016 19:51:55] I: I: Decoding values */* XMLs...
[07.01.2016 19:51:55] I: I: Baksmaling classes.dex...
[07.01.2016 19:51:59] I: I: Copying assets and libs...
[07.01.2016 19:51:59] I: I: Copying unknown files...
[07.01.2016 19:51:59] I: I: Copying original files...
[07.01.2016 19:52:00] I: ******** Decompiling finished ********
[07.01.2016 19:52:00] I: Time elapsed: 0h 0m 9s 706ms
[07.01.2016 19:56:05] I: 
[07.01.2016 19:56:05] I: 
[07.01.2016 19:56:05] I: THURSDAY 07.01.2016 19:56:05
[07.01.2016 19:56:05] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[07.01.2016 19:56:05] I: www: http://burgerz.pro
[07.01.2016 19:56:05] I: Email: az.burgerz@gmail.com
[07.01.2016 19:56:05] I: All Rights Reserved
[07.01.2016 19:56:05] I: **************************************************
[07.01.2016 19:56:05] I: Welcome to jBART v3h build 20151230.03
[07.01.2016 19:56:05] I: **************************************************
[07.01.2016 19:56:05] I: Java version: 1.8.0_45-internal
[07.01.2016 19:56:05] I: OS name: Linux
[07.01.2016 19:56:05] I: OS version: 3.13.0-66-generic
[07.01.2016 19:56:05] I: OS arch: 64 bit
[07.01.2016 19:56:05] I: Home directory: /home/igobig/Desktop/jBART-master-3H/
[07.01.2016 19:56:05] I: 
[07.01.2016 19:56:05] I: 
[07.01.2016 19:56:05] I: ******** Compiling file started ********
[07.01.2016 19:56:05] I: **** Compiling Settings.apk ****
[07.01.2016 19:56:06] I: I: Smaling smali folder into classes.dex...
[07.01.2016 19:56:15] I: I: Building resources...
[07.01.2016 19:56:33] I: I: aapt: warning: string 'advanced_text_layout' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cell_broadcast_settings_summary' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cloud_backup_section_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cloud_backup_settings_section_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cloud_restore_section_summary' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cloud_restore_section_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'cmcc_hardware_version' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'crypt_keeper_encrypt_summary' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'device_security_settings_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_control' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_earbuds' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_general' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_general_earbuds' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_general_inear' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_in_ear' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_off' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_piston_1' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_piston_100' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_piston_2' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dirac_mode_piston_youth' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_bassboost_high' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_bassboost_low' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_bassboost_normal' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_bassboost_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_effects' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_eq_enter_alert_msg' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_eq_enter_alert_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_mode_movie' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_mode_music' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_mode_off' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_movie_advance' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_music_advance' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_roomsize_high' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_roomsize_low' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_roomsize_normal' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_roomsize_summary' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'dolby_roomsize_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'enable_crypt_keeper_encrypt' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'equalizer' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'experience_optimization_category' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'fingerprint_identify_msg' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'location_access_off' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'location_access_on' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'login_account_dialog_message' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'login_account_dialog_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'login_action' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] W: W: /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res/layout/provision_page_layout.xml:4: error: Error: No resource found that matches the given name (at 'layout' with value '@miui.system:layout/provision_bg').
[07.01.2016 19:56:33] I: I: aapt: warning: string 'music_dirac_mode_piston' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_CN zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'privacy_mode_summary' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'privacy_mode_title' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_accessibility' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_battery' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_display' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_font' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_handy_mode' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_privacy' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_storage' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'search_wifi_display' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] I: I: aapt: warning: string 'title_dolby_control' has no default translation in /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res; found: zh_TW
[07.01.2016 19:56:33] W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1438450272081638835.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-5.12.31, -F, /tmp/APKTOOL6635334859813232263.tmp, -0, arsc, -0, arsc, -0, bin, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/1.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/16.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/17.apk, -S, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
[07.01.2016 19:56:33] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
[07.01.2016 19:56:33] W: 	at brut.androlib.Androlib.buildResources(Androlib.java:410)
[07.01.2016 19:56:33] W: 	at brut.androlib.Androlib.build(Androlib.java:298)
[07.01.2016 19:56:33] W: 	at brut.androlib.Androlib.build(Androlib.java:268)
[07.01.2016 19:56:33] W: 	at brut.apktool.Main.cmdBuild(Main.java:252)
[07.01.2016 19:56:33] W: 	at brut.apktool.Main.main(Main.java:109)
[07.01.2016 19:56:33] W: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1438450272081638835.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-5.12.31, -F, /tmp/APKTOOL6635334859813232263.tmp, -0, arsc, -0, arsc, -0, bin, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/1.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/16.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/17.apk, -S, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
[07.01.2016 19:56:33] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
[07.01.2016 19:56:33] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
[07.01.2016 19:56:33] W: 	... 5 more
[07.01.2016 19:56:33] W: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1438450272081638835.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-5.12.31, -F, /tmp/APKTOOL6635334859813232263.tmp, -0, arsc, -0, arsc, -0, bin, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/1.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/16.apk, -I, /home/igobig/Desktop/jBART-master-3H/data/frameworks/17.apk, -S, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/res, -M, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk/AndroidManifest.xml]
[07.01.2016 19:56:33] W: 	at brut.util.OS.exec(OS.java:119)
[07.01.2016 19:56:33] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:421)
[07.01.2016 19:56:33] W: 	... 6 more
[07.01.2016 19:56:34] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -Xms444m, -Xmx444m, -jar, /home/igobig/Desktop/jBART-master-3H/data/tools/lib/apktool-3.0.9-bz-small.jar, b, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/decompiled/Settings.apk, -f, -c, -p, /home/igobig/Desktop/jBART-master-3H/data/frameworks, -o, /home/igobig/Desktop/jBART-master-3H/Settings.apk.bzprj/compiled/Settings.apk]
[07.01.2016 19:56:34] I: Time elapsed: 0h 0m 28s 265ms

**Comment by BurgerZ** [comment] 2016-01-07 14:06
Duplicate of #135

**Closed** 2016-01-07 14:06 UTC

**Comment by igobig** [comment] 2016-01-07 16:54
Working Thanks @BurgerZ
